FROM --platform=linux/amd64 continuumio/miniconda3:23.3.1-0-alpine
ENV DEBIAN_FRONTEND=noninteractive

# RUN apt-get update && apt-get install -y build-essential
RUN conda create -n bptenv
RUN conda install -n bptenv -c conda-forge make pandoc sphinx nbsphinx jinja2 sphinx-reredirects ipython_genutils furo

ENTRYPOINT ["/opt/conda/bin/conda", "run", "-n", "bptenv", "--no-capture-output", "--live-stream"]

